// Tests generated by Chinomatic (Qwen2.5-Coder:32b) via REST API — Feb 22, 2026
// Minor fixes: paths, selectors, mock paths
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import NewCaptureModal from './NewCaptureModal'

// Mock window.location.reload
Object.defineProperty(window, 'location', {
  value: { reload: vi.fn() },
  writable: true,
})

beforeEach(() => {
  vi.clearAllMocks()
  global.fetch = vi.fn().mockResolvedValue({
    ok: true,
    json: () => Promise.resolve({ ok: true }),
  }) as any
})

describe('<NewCaptureModal /> Component Tests', () => {
  it('renders "+" button', () => {
    render(<NewCaptureModal />)
    expect(screen.getByText('+')).toBeInTheDocument()
  })

  it('clicking "+" opens the modal', () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    expect(screen.getByPlaceholderText('Escribe tu captura...')).toBeInTheDocument()
  })

  it('pressing Escape closes modal', async () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    const textarea = screen.getByPlaceholderText('Escribe tu captura...')
    fireEvent.keyDown(textarea, { key: 'Escape' })
    await waitFor(() => {
      expect(screen.queryByPlaceholderText('Escribe tu captura...')).not.toBeInTheDocument()
    })
  })

  it('submit button disabled when body is empty', () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    const submitButton = screen.getByText('Guardar')
    expect(submitButton).toBeDisabled()
  })

  it('API POST called with correct data on submit', async () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    const textarea = screen.getByPlaceholderText('Escribe tu captura...')
    fireEvent.change(textarea, { target: { value: 'Test Capture' } })
    fireEvent.click(screen.getByText('Guardar'))

    await waitFor(() => {
      expect(fetch).toHaveBeenCalledWith('/api/capture', expect.objectContaining({
        method: 'POST',
        body: JSON.stringify({ body: 'Test Capture', type: 'idea', domain: 'sandbox' }),
      }))
    })
  })

  it('type pills work — clicking changes active type', () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    const taskPill = screen.getByRole('button', { name: 'task' })
    fireEvent.click(taskPill)
    // After clicking task, its style should change (bg: var(--text))
    expect(taskPill).toHaveStyle({ background: 'var(--text)' })
  })

  it('Ctrl+Enter submits the form', async () => {
    render(<NewCaptureModal />)
    fireEvent.click(screen.getByText('+'))
    const textarea = screen.getByPlaceholderText('Escribe tu captura...')
    fireEvent.change(textarea, { target: { value: 'Ctrl+Enter test' } })
    fireEvent.keyDown(textarea, { key: 'Enter', ctrlKey: true })
    await waitFor(() => {
      expect(fetch).toHaveBeenCalled()
    })
  })
})
