'use client'
// Generated by Chinomatic (Qwen2.5-Coder:32b) — Feb 22, 2026
// Fixed by TijaroBot: axios→fetch, 'use client', button type, dynamic domains

import { useState, useEffect } from 'react'

const TYPES = ['task', 'idea', 'creencia', 'reflexion', 'referencia', 'regla']

const NewCaptureModal: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false)
  const [body, setBody] = useState('')
  const [type, setType] = useState<string>('idea')
  const [domain, setDomain] = useState<string>('sandbox')
  const [loading, setLoading] = useState(false)
  const [domains, setDomains] = useState<string[]>(['sandbox'])

  useEffect(() => {
    fetch('/api/domains')
      .then(r => r.json())
      .then(data => {
        if (data.domains?.length) setDomains(data.domains.map((d: any) => d.slug))
      })
      .catch(() => {})
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!body.trim()) return
    setLoading(true)
    try {
      await fetch('/api/capture', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ body, type, domain }),
      })
      setBody('')
      setIsOpen(false)
      window.location.reload()
    } catch (error) {
      console.error('Failed to create capture:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Escape') {
      setIsOpen(false)
    } else if (e.ctrlKey && e.key === 'Enter') {
      handleSubmit(e as any)
    }
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 w-10 h-10 rounded-full shadow-lg text-xl font-light flex items-center justify-center transition-opacity hover:opacity-80"
        style={{ background: 'var(--text)', color: 'var(--bg)' }}
        title="Nueva captura"
      >
        +
      </button>

      {isOpen && (
        <div
          className="fixed inset-0 flex items-center justify-center z-50"
          style={{ background: 'rgba(0,0,0,0.8)' }}
          onClick={(e) => { if (e.target === e.currentTarget) setIsOpen(false) }}
        >
          <form
            onSubmit={handleSubmit}
            className="rounded-xl p-6 w-full max-w-md shadow-xl"
            style={{ background: 'var(--bg)', border: '1px solid var(--border)' }}
          >
            <textarea
              autoFocus
              value={body}
              onChange={(e) => setBody(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Escribe tu captura..."
              rows={5}
              className="w-full p-3 rounded-lg mb-4 resize-none text-[14px] outline-none"
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                color: 'var(--text)',
              }}
            />

            {/* Type pills */}
            <div className="mb-4">
              <span className="block text-[11px] mb-2" style={{ color: 'var(--text-tertiary)' }}>Tipo</span>
              <div className="flex flex-wrap gap-2">
                {TYPES.map((t) => (
                  <button
                    key={t}
                    type="button"
                    onClick={() => setType(t)}
                    className="px-3 py-1 rounded-full text-[12px] transition-colors"
                    style={{
                      background: type === t ? 'var(--text)' : 'var(--surface)',
                      color: type === t ? 'var(--bg)' : 'var(--text-secondary)',
                      border: '1px solid var(--border)',
                    }}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>

            {/* Domain */}
            <div className="mb-5">
              <span className="block text-[11px] mb-2" style={{ color: 'var(--text-tertiary)' }}>Dominio</span>
              <select
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                className="w-full px-3 py-2 rounded-lg text-[13px] outline-none"
                style={{
                  background: 'var(--surface)',
                  border: '1px solid var(--border)',
                  color: 'var(--text)',
                }}
              >
                {domains.map((d) => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>

            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setIsOpen(false)}
                className="flex-1 py-2 rounded-lg text-[13px] transition-opacity hover:opacity-70"
                style={{ background: 'var(--surface)', color: 'var(--text-secondary)' }}
              >
                Cancelar
              </button>
              <button
                type="submit"
                disabled={loading || !body.trim()}
                className="flex-1 py-2 rounded-lg text-[13px] font-medium transition-opacity hover:opacity-90 disabled:opacity-40"
                style={{ background: 'var(--text)', color: 'var(--bg)' }}
              >
                {loading ? 'Guardando...' : 'Guardar'}
              </button>
            </div>
          </form>
        </div>
      )}
    </>
  )
}

export default NewCaptureModal
